<?php

use yii\web\View;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Html;

/**
 * @var $this View
 * @var $model \super\ticket\models\forms\SuperTicketBulkForm
 */

$js = <<<JS
 jQuery(document).ready(function () {
        jQuery('body').on('beforeSubmit', 'form#recipient-form', function () {
            var form = jQuery(this);
            var checkboxex = jQuery('#ticket-grid');
            
            // return false if form still have some validation errors
            if (form.find('.has-error').length) 
            {
                return false;
            }
            
            var data = form.serialize();
            data += "&" + jQuery('.ticket-selection:checked', checkboxex).serialize();
            
            // submit form
            jQuery.ajax({
                url    : form.attr('action'),
                type   : 'post',
                data   : data,
                success: function (response) {
                    debugger;
                    var getupdatedata = jQuery(response).find('#filter_id_test');
                    // jQuery.pjax.reload('#note_update_id'); for pjax update
                    jQuery('#yiiikap').html(getupdatedata);
                    //console.log(getupdatedata);
                },
                error  : function () {
                    console.log('internal server error');
                }
            });
            
            return false;
         });
    });
JS;

$this->registerJs($js);


?>
    <div class="super-invte-form">

        <?php $form = ActiveForm::begin([
                'id' => 'recipient-form',
                'options' => ['data-pjax' => true],
                'action' => ['/super/api/ticket/bulk-edit']
            ]
        );
        ?>

        <div class="">
            <p>

                <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                $form->field($model, 'status')->dropDownList(
                    \yii\helpers\ArrayHelper::map($model->getAvailableStatuses(), 'id', 'statusName'),
                    [
                        'prompt' => Yii::t('app', 'Select'),
                        'disabled' => (isset($relAttributes) && isset($relAttributes['agent_id'])),
                    ]
                ); ?>

            </p>

            <?php echo $form->errorSummary($model); ?>

            <?= Html::submitButton(
                '<span class="glyphicon glyphicon-check"></span> ' .
                Yii::t('super', 'Add'),
                [
                    'id' => 'save-' . $model->formName(),
                    'class' => 'btn btn-success'
                ]
            );
            ?>

            <?php ActiveForm::end(); ?>

        </div>

    </div>