<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\bootstrap4\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var super\ticket\models\SuperTicketSla $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="super-ticket-sla-form">

    <?php $form = ActiveForm::begin([
    'id' => 'SuperTicketSla',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-danger',
    'fieldConfig' => [
             'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
             'horizontalCssClasses' => [
                 'label' => 'col-sm-2',
                 #'offset' => 'col-sm-offset-4',
                 'wrapper' => 'col-sm-8',
                 'error' => '',
                 'hint' => '',
             ],
         ],
    ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>
            

<!-- attribute name -->
			<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

<!-- attribute domain_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'scheduling_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(super\ticket\models\SuperTicketSlaSchedule::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('app', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['domain_id'])),
    ]
); ?>

<!-- attribute agent_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
$form->field($model, 'customer_id')->dropDownList(
    \yii\helpers\ArrayHelper::map(super\ticket\models\SuperCustomer::find()->all(), 'id', 'name'),
    [
        'prompt' => Yii::t('app', 'Select'),
        'disabled' => (isset($relAttributes) && isset($relAttributes['agent_id'])),
    ]
); ?>

<!-- attribute grace_period -->
			<?= $form->field($model, 'grace_period')->textInput() ?>

        </p>
        <?php $this->endBlock(); ?>
        
        <?=
    Tabs::widget(
                 [
                    'encodeLabels' => false,
                    'items' => [ 
                        [
    'label'   => Yii::t('models', 'SuperTicketSla'),
    'content' => $this->blocks['main'],
    'active'  => true,
],
                    ]
                 ]
    );
    ?>
        <hr/>

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
        '<span class="glyphicon glyphicon-check"></span> ' .
        ($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Save')),
        [
        'id' => 'save-' . $model->formName(),
        'class' => 'btn btn-success'
        ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

